<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Nishkarsh" failures="1" tests="1" name="FirefoxTest(failed)" time="0.058" errors="0" timestamp="2025-06-21T19:24:44 IST">
  <testcase classname="TestCases.herokuapp_Local" name="ValidLogin" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at Utils.CSVReaderUtil.loginDataProvider(CSVReaderUtil.java:39)
... 19 more
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- ValidLogin -->
  <testcase classname="TestCases.herokuapp_Local" name="inValidLogin" time="0.0">
    <ignored/>
  </testcase> <!-- inValidLogin -->
  <testcase classname="TestCases.herokuapp_Local" name="JsAlert" time="0.0">
    <ignored/>
  </testcase> <!-- JsAlert -->
</testsuite> <!-- FirefoxTest(failed) -->
